[package]
name = "lf"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "7.0.0"
atty = "0.2.14"
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
thiserror = "2.0.17"
